source_container = "berbalang-test"
container_profiles = [
    "berbalang"
]

[[test_spec]]
name = "derp-test"
test_cmd = "derp"
nr_of_test_runs = 4
test_length = 3600

[[test_spec]]
name = "herp-test"
test_cmd = "herp"
nr_of_test_runs = 27
test_length = 3600

[[test_spec]]
name = "silly-test"
test_cmd = "Something silly"
nr_of_test_runs = 255
test_length = 3600
