source_container = "berbalang-test"

[[test_spec]]
test_cmd = "derp"
nr_of_test_runs = 4
test_length = 3600

[[test_spec]]
test_cmd = "herp"
nr_of_test_runs = 27
test_length = 3600

[[test_spec]]
test_cmd = "Something silly"
nr_of_test_runs = 255
test_length = 3600
